version: "3.5"
services:
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
    networks: 
      - demo
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: app
    depends_on:
      - db
    links:
      - db
    restart: on-failure
    ports:
      - "5000:8080"
    networks: 
      - demo

networks:
  demo:
    name: demo_network