version: "3"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    restart: on-failure
    ports:
      - "8081:8080"
